// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel_list_API.Data;

namespace Travel_list_API.Migrations
{
    [DbContext(typeof(Context))]
    partial class TravelListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Travel_list_API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelListId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Opmaak",
                            TravelListId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technologie",
                            TravelListId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bad",
                            TravelListId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kledij",
                            TravelListId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Opmaak",
                            TravelListId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Technologie",
                            TravelListId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bad",
                            TravelListId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kledij",
                            TravelListId = 2
                        });
                });

            modelBuilder.Entity("Travel_list_API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2021, 1, 15, 21, 10, 21, 86, DateTimeKind.Local).AddTicks(5753),
                            Email = "client@gmail.com",
                            FirstName = "Pog",
                            LastName = "Champ"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2021, 1, 15, 21, 10, 21, 88, DateTimeKind.Local).AddTicks(3668),
                            Email = "client2@gmail.com",
                            FirstName = "Ayaya",
                            LastName = "Clap"
                        });
                });

            modelBuilder.Entity("Travel_list_API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Added")
                        .HasColumnType("bit");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelListId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Added = false,
                            Amount = 1,
                            Category = "Opmaak",
                            Name = "Kam",
                            TravelListId = 1
                        },
                        new
                        {
                            Id = 2,
                            Added = true,
                            Amount = 2,
                            Category = "Technologie",
                            Name = "Laptop",
                            TravelListId = 1
                        },
                        new
                        {
                            Id = 3,
                            Added = true,
                            Amount = 5,
                            Category = "Bad",
                            Name = "Handdoek",
                            TravelListId = 2
                        },
                        new
                        {
                            Id = 4,
                            Added = false,
                            Amount = 3,
                            Category = "Bad",
                            Name = "Tandenborstel",
                            TravelListId = 2
                        },
                        new
                        {
                            Id = 5,
                            Added = false,
                            Amount = 1,
                            Category = "Technologie",
                            Name = "Batterij",
                            TravelListId = 3
                        },
                        new
                        {
                            Id = 6,
                            Added = true,
                            Amount = 8,
                            Category = "Bad",
                            Name = "Shampoo",
                            TravelListId = 4
                        },
                        new
                        {
                            Id = 7,
                            Added = false,
                            Amount = 6,
                            Category = "Kledij",
                            Name = "Broek",
                            TravelListId = 4
                        },
                        new
                        {
                            Id = 8,
                            Added = true,
                            Amount = 9,
                            Category = "Kledij",
                            Name = "Sjaal",
                            TravelListId = 5
                        });
                });

            modelBuilder.Entity("Travel_list_API.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("EndLatitude")
                        .HasColumnType("float");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("float");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<int>("TravelListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelListId")
                        .IsUnique();

                    b.ToTable("Itineraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndLatitude = 41.385063000000002,
                            EndLongitude = 2.1734040000000001,
                            StartLatitude = 51.054340000000003,
                            StartLongitude = 3.7174239999999998,
                            TravelListId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndLatitude = 48.856613000000003,
                            EndLongitude = 2.3522219999999998,
                            StartLatitude = 51.054340000000003,
                            StartLongitude = 3.7174239999999998,
                            TravelListId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndLatitude = 52.370215999999999,
                            EndLongitude = 4.895168,
                            StartLatitude = 51.054340000000003,
                            StartLongitude = 3.7174239999999998,
                            TravelListId = 3
                        });
                });

            modelBuilder.Entity("Travel_list_API.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelListId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Travel_list_API.Models.TravelList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TravelLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            EndDate = new DateTime(2021, 1, 20, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(3608),
                            Name = "Spanje",
                            StartDate = new DateTime(2021, 1, 15, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(3277)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            EndDate = new DateTime(2021, 1, 20, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4174),
                            Name = "Frankrijk",
                            StartDate = new DateTime(2021, 1, 15, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4153)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            EndDate = new DateTime(2021, 1, 20, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4191),
                            Name = "Nederland",
                            StartDate = new DateTime(2021, 1, 15, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4188)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            EndDate = new DateTime(2021, 1, 20, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4197),
                            Name = "Duitsland",
                            StartDate = new DateTime(2021, 1, 15, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4195)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 2,
                            EndDate = new DateTime(2021, 1, 20, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4203),
                            Name = "Noorwegen",
                            StartDate = new DateTime(2021, 1, 15, 21, 10, 21, 89, DateTimeKind.Local).AddTicks(4201)
                        });
                });

            modelBuilder.Entity("Travel_list_API.Models.Category", b =>
                {
                    b.HasOne("Travel_list_API.Models.TravelList", null)
                        .WithMany("Categories")
                        .HasForeignKey("TravelListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Travel_list_API.Models.Item", b =>
                {
                    b.HasOne("Travel_list_API.Models.TravelList", null)
                        .WithMany("Items")
                        .HasForeignKey("TravelListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Travel_list_API.Models.Itinerary", b =>
                {
                    b.HasOne("Travel_list_API.Models.TravelList", null)
                        .WithOne("Itinerary")
                        .HasForeignKey("Travel_list_API.Models.Itinerary", "TravelListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Travel_list_API.Models.Task", b =>
                {
                    b.HasOne("Travel_list_API.Models.TravelList", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TravelListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Travel_list_API.Models.TravelList", b =>
                {
                    b.HasOne("Travel_list_API.Models.Client", null)
                        .WithMany("TravelLists")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
